//- Delete relationships
CALL apoc.periodic.iterate(
    "MATCH ()-[r:SIMILAR_SHIPPER|SIMILAR_CONSIGNEE|SIMILAR_NOTIFYPARTY|SIMILAR_CARRIER|SIMILAR_PORTOFLADING|SIMILAR_PORTOFUNLADING]-() RETURN r",
    "DELETE r",
    {batchSize:50000})
